import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col pt-30 md:overscroll-y-none ${montserrat.className} antialiased`}
      >
        <main className="flex flex-1 flex-col items-center justify-center px-30">
          {children}
        </main>
        <footer className="relative inset-y-0 z-50 h-40 w-full">
          <Image
            className="absolute bottom-0 w-full"
            src="/Vector.png"
            alt=""
            width={1440}
            height={111}
            priority
          />
          <Image
            className="absolute bottom-0 w-full"
            src="/Vector2.png"
            alt=""
            width={1440}
            height={111}
            priority
          />
        </footer>
      </body>
    </html>
  )
}
